<a href="https://colab.research.google.com/github/m00n07/mineria_de_datos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## 1er **Parcial**

### Introduccion

#### Conceptos

La minería de datos es un campo en constante evolución que ofrece numerosas oportunidades de investigación. Desde técnicas y herramientas hasta aplicaciones prácticas y consideraciones éticas, hay un amplio espectro de temas que se pueden explorar para obtener conocimientos valiosos a partir de grandes volúmenes de datos.


#### Ciencia de Datos

La ciencia de datos es un campo interdisciplinario que utiliza métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e información a partir de datos estructurados y no estructurados. Esta disciplina combina diversas disciplinas como la estadística, la informática, la matemática, la visualización de datos y el dominio del área de aplicación para analizar datos complejos y resolver problemas del mundo real. La ciencia de datos se centra en el ciclo de vida completo de la gestión de datos, desde la recolección hasta la interpretación y comunicación de resultados.

Help and Documentation in Python

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?


In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
def square(a):
    """Return the square of a."""
    return a ** 2
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
from itertools import combinations

IPython Magic Commands

In [ ]:
# sirve para evaluar el deseméño de una exopresion en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

86.6 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# con doble % podemos evaluar el desempeño en cuanto al tiempo de mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

83.3 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/


/content


In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '78546de579a8',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
# importa numpy y renombralo como np
import numpy as np

In [ ]:
# arregaglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# le estamos diciendo que sea flotante de 32 bits
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int32')

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# lista de comprension que genere un rango en dos argumentos el inicio y el limite
# se genera una matriz bidi
# cuando el argumento de np.array es una iteracion anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# lista de python
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

Creating Arrays from Scratch

In [ ]:
import numpy as np

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3, 3))

array([[0.17031218, 0.77262037, 0.03200332],
       [0.48338849, 0.59385632, 0.51959536],
       [0.66287834, 0.96275487, 0.59637971]])

In [ ]:
# la campana de gauss
# el 1er numero es la media es la dev estandar y el tamaño de la matriz o el num de datos que salen
np.random.normal(0, 1, (3, 3))

array([[-1.53850755, -0.95520514, -1.29578649],
       [-1.50889849, -0.14630574,  1.41772312],
       [-0.61814173, -1.55243333,  1.83080191]])

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[1, 0, 0],
       [7, 3, 4],
       [7, 9, 2]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [ ]:
np.random.seed(0)  # semilla

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
# bum d edimensiones
print("x3 ndim: ", x3.ndim)
# forma
print("x3 shape:", x3.shape)
# tamaño
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)

dtype: int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

np.int64(5)

In [ ]:
x1[3]

np.int64(3)

In [ ]:
x1[-1]

np.int64(9)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0,2]

np.int64(2)

In [ ]:
x2[-1,-1]

np.int64(7)

In [ ]:
x2[-1,-1] = 2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

#### Analisis Estadistico Básico con Numpy

Media (Mean)

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [ ]:
mediana = np.median(data)
mediana

np.float64(3.0)

Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


#### Cuadros estadisticos

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [2]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [3]:
df.tail()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
55  19/01/2026 20:22:15               176535                               25   
56  19/01/2026 20:22:29               179862                               21   
57  19/01/2026 20:22:32               178378                               22   
58  19/01/2026 20:22:50               177451                               22   
59  19/01/2026 20:23:15               179804                               21   

   ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
55                                          Si                           No   
56                                          Si                           No   
57                                          Si                           No   
58                                          Si                           No   
59                                          Si                           No   

   ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
55                        Si    25         True      False           True  
56                        Si    21         True      False           True  
57                        Si    22         True      False           True  
58                        Si    22         True      False           True  
59                        Si    21         True      False           True

In [4]:
df.head(3)

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True

In [5]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [6]:
print(f'ndarray edad: {edad}')

ndarray edad: [22. 21. 26. 21. 24. 22. 22. 21. 23. 22. 23. 22. 23. 22. 22. 22. 22. 22.
 21. 24. 21. 23. 24. 21. 22. 22. 24. 21. 23. 20. 22. 21. 22. 20. 24. 24.
 21. 25. 23. 23. 23. 21. 23. 23. 22. 24. 22. 22. 22. 26. 20. 22. 21. 21.
 22. 25. 21. 22. 22. 21.]


In [8]:
print(f'ndarray edad primeros 5 elementos: {edad[:5]}')
print(f'ndarray prog_py primeros 5 elementos: {prog_py[:5]}')
print(f'ndarray usa_colab primeros 5 elementos: {usa_colab[:5]}')
print(f'ndarray cuenta_github ultimos 5 elementos: {cuenta_gh[-5:]}')

ndarray edad primeros 5 elementos: [22. 21. 26. 21. 24.]
ndarray prog_py primeros 5 elementos: [ True  True  True  True  True]
ndarray usa_colab primeros 5 elementos: [False False  True  True False]
ndarray cuenta_github ultimos 5 elementos: [ True  True  True  True  True]


In [13]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),  # coeficiente de variacion
}
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [14]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [16]:
print(f'frecuencia de utilizar Python: {freq_python}')
print(f'frecuencia de utilizar Google Colab: {freq_colab}')
print(f'frecuencia de tener cuenta de GitHub: {freq_gh}')

frecuencia de utilizar Python: {'Si': 54, 'No': 6}
frecuencia de utilizar Google Colab: {'Si': 18, 'No': 42}
frecuencia de tener cuenta de GitHub: {'Si': 52, 'No': 8}


In [17]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [18]:
print(f'tabla Python vs Colab:\n{tab_py_colab}')
print(f'tabla Python vs GitHub:\n{tab_py_gh}')
print(f'tabla Colab vs GitHub:\n{tab_colab_gh}')

tabla Python vs Colab:
[[ 6  0]
 [36 18]]
tabla Python vs GitHub:
[[ 1  5]
 [ 7 47]]
tabla Colab vs GitHub:
[[ 5 37]
 [ 3 15]]


In [20]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

In [22]:
summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})