<a href="https://colab.research.google.com/github/m00n07/mineria_de_datos/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## 1er **Parcial**

### Introduccion

#### Conceptos

La minería de datos es un campo en constante evolución que ofrece numerosas oportunidades de investigación. Desde técnicas y herramientas hasta aplicaciones prácticas y consideraciones éticas, hay un amplio espectro de temas que se pueden explorar para obtener conocimientos valiosos a partir de grandes volúmenes de datos.


#### Ciencia de Datos

La ciencia de datos es un campo interdisciplinario que utiliza métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e información a partir de datos estructurados y no estructurados. Esta disciplina combina diversas disciplinas como la estadística, la informática, la matemática, la visualización de datos y el dominio del área de aplicación para analizar datos complejos y resolver problemas del mundo real. La ciencia de datos se centra en el ciclo de vida completo de la gestión de datos, desde la recolección hasta la interpretación y comunicación de resultados.

Help and Documentation in Python

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?


In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
def square(a):
    """Return the square of a."""
    return a ** 2
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
from itertools import combinations

IPython Magic Commands

In [ ]:
# sirve para evaluar el deseméño de una exopresion en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

86.6 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
# con doble % podemos evaluar el desempeño en cuanto al tiempo de mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

83.3 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [9]:
!ls

sample_data


In [11]:
!pwd

/content


In [12]:
!echo "printing from the shell"

printing from the shell


In [13]:
contents = !ls

In [14]:
print(contents)

['sample_data']


In [15]:
directory = !pwd

In [16]:
print(directory)

['/content']


In [17]:
type(directory)

IPython.utils.text.SList

In [18]:
message = "hello from Python"

In [19]:
!echo {message}

hello from Python


In [24]:
%cd /content/


/content


In [25]:
!ls

sample_data


In [26]:
%cd sample_data/

/content/sample_data


In [27]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [28]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [29]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '78546de579a8',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [31]:
# importa numpy y renombralo como np
import numpy as np

In [33]:
# arregaglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [35]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [37]:
# le estamos diciendo que sea flotante de 32 bits
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [38]:
np.array([1, 2, 3, 4], dtype='int32')

array([1, 2, 3, 4], dtype=int32)

In [42]:
# lista de comprension que genere un rango en dos argumentos el inicio y el limite
# se genera una matriz bidi
# cuando el argumento de np.array es una iteracion anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [46]:
# lista de python
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]