<a href="https://colab.research.google.com/github/m00n07/mineria_de_datos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## 1er **Parcial**

### Introduccion

#### Conceptos

La minería de datos es un campo en constante evolución que ofrece numerosas oportunidades de investigación. Desde técnicas y herramientas hasta aplicaciones prácticas y consideraciones éticas, hay un amplio espectro de temas que se pueden explorar para obtener conocimientos valiosos a partir de grandes volúmenes de datos.


#### Ciencia de Datos

La ciencia de datos es un campo interdisciplinario que utiliza métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e información a partir de datos estructurados y no estructurados. Esta disciplina combina diversas disciplinas como la estadística, la informática, la matemática, la visualización de datos y el dominio del área de aplicación para analizar datos complejos y resolver problemas del mundo real. La ciencia de datos se centra en el ciclo de vida completo de la gestión de datos, desde la recolección hasta la interpretación y comunicación de resultados.

Help and Documentation in Python

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?


In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
def square(a):
    """Return the square of a."""
    return a ** 2
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

In [ ]:
from itertools import combinations

IPython Magic Commands

In [ ]:
# sirve para evaluar el deseméño de una exopresion en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

86.6 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# con doble % podemos evaluar el desempeño en cuanto al tiempo de mas de una linea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

83.3 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/


/content


In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '78546de579a8',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
# importa numpy y renombralo como np
import numpy as np

In [ ]:
# arregaglo lineal de enteros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# le estamos diciendo que sea flotante de 32 bits
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int32')

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# lista de comprension que genere un rango en dos argumentos el inicio y el limite
# se genera una matriz bidi
# cuando el argumento de np.array es una iteracion anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# lista de python
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

Creating Arrays from Scratch

In [6]:
import numpy as np

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((3, 3))

array([[0.17031218, 0.77262037, 0.03200332],
       [0.48338849, 0.59385632, 0.51959536],
       [0.66287834, 0.96275487, 0.59637971]])

In [16]:
# la campana de gauss
# el 1er numero es la media es la dev estandar y el tamaño de la matriz o el num de datos que salen
np.random.normal(0, 1, (3, 3))

array([[-1.53850755, -0.95520514, -1.29578649],
       [-1.50889849, -0.14630574,  1.41772312],
       [-0.61814173, -1.55243333,  1.83080191]])

In [17]:
np.random.randint(0, 10, (3, 3))

array([[1, 0, 0],
       [7, 3, 4],
       [7, 9, 2]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [20]:
np.random.seed(0)  # semilla

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [24]:
# bum d edimensiones
print("x3 ndim: ", x3.ndim)
# forma
print("x3 shape:", x3.shape)
# tamaño
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [22]:
print("dtype:", x3.dtype)

dtype: int64


In [25]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

np.int64(5)

In [29]:
x1[3]

np.int64(3)

In [30]:
x1[-1]

np.int64(9)

In [31]:
x1[-2]

np.int64(7)

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
x2[0,2]

np.int64(2)

In [36]:
x2[-1,-1]

np.int64(7)

In [37]:
x2[-1,-1] = 2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

#### Analisis Estadistico Básico con Numpy

Media (Mean)

In [38]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [39]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [41]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [43]:
mediana = np.median(data)
mediana

np.float64(3.0)

Varianza y Desviación Estándar

In [45]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [46]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [49]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
